# Generated by Django 3.2.7 on 2021-12-27 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 8, 31, 29, 328538)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='packets_lost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='rtt_avg_ms',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
