# Generated by Django 3.2.7 on 2021-12-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211228_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='host_type',
            field=models.ForeignKey(help_text='The host type can be a Desktop, Antenna, Router, AP, Switch...', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hosttype'),
        ),
    ]
