# Generated by Django 3.2.7 on 2022-02-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211230_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='last_date_alive',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
