# Generated by Django 3.2.7 on 2022-02-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_host_last_date_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
